version: '3.4'

services:

  webapi:
    container_name: 'sedowebapi2'
    image: 'sedoocker/mari7:nov10_7'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $HOME/docker/volumes/logs:/logs
    ports:
     - "5000:80"
    depends_on:
     - "postgres"
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'pg-docker'
    image: postgres
    ports:
     - "5432:5432"
    restart: always
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "sedo123"
      POSTGRES_DB: "Mari7"
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge